spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:todolist # h2 database 連接位址
      driver-class-name: org.h2.Driver # 配置driver
      username: sa # database 用戶名
      password:  # database 密碼
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: public
        event:
          merge:
            entity_copy_observer: allow
    open-in-view: true