spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql:/localhost:8080/demoTable
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 2
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        event:
          merge:
            entity_copy_observer: allow
    open-in-view: true