spring:
  cache:
    jcache:
      config: ehcache3.xml
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  freemarker:
    enabled: true
    cache: true
    suffix: .ftl
    settings:
      template_exception_handler: ignore
  profiles:
    active: test
  session:
    store-type: none
  jmx:
    enabled: false
  web:
    resources:
      cache:
        period: 86400s
server:
  servlet:
    session:
      cookie:
        name: PHPSESSIONID
      tracking-modes: COOKIE