server:
  port: 8081
  path: /home

coin-data:
  chartName:
  disclaimer:
  updated:
  updatedISO:
  updateDuk:
  detailList[0]:
    code:
    symbol:
    rate:
    description:
    rateFloat:
coin-detail:
  code:
  symbol:
  rate:
  description:
  rateFloat:
